services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: guestbook
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - uid
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 3333:80
    depends_on:
      - db
